/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tester;
import TwoDimensionalLists.*;
import LedAnimations.*;
import java.io.*;
import javax.swing.*;
/**
 *
 * @author OmarR
 */
public class Editor extends javax.swing.JFrame {

    /**
     * Creates new form TESTER
     */
    public Editor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton_Graficar = new javax.swing.JButton();
        jButton_TESTER2 = new javax.swing.JButton();
        jButton_U = new javax.swing.JButton();
        jButton_D = new javax.swing.JButton();
        jButton_R = new javax.swing.JButton();
        jButton_L = new javax.swing.JButton();
        jButton_BL = new javax.swing.JButton();
        jButton_BR = new javax.swing.JButton();
        jButton_BD = new javax.swing.JButton();
        jButton_BU = new javax.swing.JButton();
        jButton_TESTER1 = new javax.swing.JButton();
        jButton_GuardarComo = new javax.swing.JButton();
        jButton_Abrir = new javax.swing.JButton();
        jButton_Guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jTextPane1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 560, 310);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(50, 10, 140, 30);

        jLabel1.setText("Texto:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 37, 30);

        jButton_Graficar.setText("Graficar");
        jButton_Graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GraficarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Graficar);
        jButton_Graficar.setBounds(200, 10, 120, 30);

        jButton_TESTER2.setText("TESTER2");
        jButton_TESTER2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TESTER2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_TESTER2);
        jButton_TESTER2.setBounds(450, 10, 110, 30);

        jButton_U.setText("ARRIBA");
        jButton_U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_U);
        jButton_U.setBounds(610, 10, 100, 25);

        jButton_D.setText("ABAJO");
        jButton_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_D);
        jButton_D.setBounds(610, 40, 100, 25);

        jButton_R.setText("DERECHA");
        jButton_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_R);
        jButton_R.setBounds(610, 70, 100, 25);

        jButton_L.setText("IZQUIERDA");
        jButton_L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_L);
        jButton_L.setBounds(610, 100, 100, 25);

        jButton_BL.setText("BUCLE IZQUIERDA");
        jButton_BL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BLActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_BL);
        jButton_BL.setBounds(570, 220, 140, 25);

        jButton_BR.setText("BUCLE DERECHA");
        jButton_BR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BRActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_BR);
        jButton_BR.setBounds(570, 190, 140, 25);

        jButton_BD.setText("BUCLE ABAJO");
        jButton_BD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BDActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_BD);
        jButton_BD.setBounds(570, 160, 140, 25);

        jButton_BU.setText("BUCLE ARRIBA");
        jButton_BU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BUActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_BU);
        jButton_BU.setBounds(570, 130, 140, 25);

        jButton_TESTER1.setText("TESTER");
        jButton_TESTER1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TESTER1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_TESTER1);
        jButton_TESTER1.setBounds(329, 10, 110, 30);

        jButton_GuardarComo.setText("Guardar como");
        jButton_GuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarComoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GuardarComo);
        jButton_GuardarComo.setBounds(570, 310, 140, 25);

        jButton_Abrir.setText("Abrir");
        jButton_Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AbrirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Abrir);
        jButton_Abrir.setBounds(570, 250, 140, 25);

        jButton_Guardar.setText("Guardar");
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Guardar);
        jButton_Guardar.setBounds(570, 280, 140, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    SwingGraphicsLedScreen graficador;
    private void jButton_GraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GraficarActionPerformed
        TwoDimensionalLists PantallaLed = new TwoDimensionalLists(jTextField1.getText(),'⬛', ' ');
        graficador = new SwingGraphicsLedScreen(PantallaLed, jTextPane1);
        graficador.GraphLedDisplay(jTextField1.getText());
    }//GEN-LAST:event_jButton_GraficarActionPerformed

   
    private void jButton_TESTER2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TESTER2ActionPerformed
           //String secuencia = "RIGHT:40-500_UP:8-1000_DOWN:16-250_LEFT:40-125|BUCLE";
           /*String secuencia = "RIGHT:4-500_UP:3-1000_DOWN:10-250_LEFT:15-125/VIEW";
           graficador.SequentialAnimation(secuencia);*/
           //1-AGREGAR AGRANDAR LETRA, ACHICAR LETRA
           //2-AGREGAR LETRAS, SIMBOLOS, ESPACIO
           //3-CREAR UN ARCHIVO NUEVO, ABRIR ARCHIVO, GUARDAR COMO, GUARDAR
           //4-EXPORTAR A C MICHI XD
           graficador.DecreaseTextSize();
           
    }//GEN-LAST:event_jButton_TESTER2ActionPerformed

    private void jButton_UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UActionPerformed
        graficador.MoveOneStepUp();
    }//GEN-LAST:event_jButton_UActionPerformed

    private void jButton_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DActionPerformed
        graficador.MoveOneStepDown();
    }//GEN-LAST:event_jButton_DActionPerformed

    private void jButton_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RActionPerformed
        graficador.MoveOneStepRight();
    }//GEN-LAST:event_jButton_RActionPerformed

    private void jButton_LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LActionPerformed
        graficador.MoveOneStepLeft();
    }//GEN-LAST:event_jButton_LActionPerformed

    private void jButton_BLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BLActionPerformed
       graficador.Animation("LEFT", 4, 500);  
    }//GEN-LAST:event_jButton_BLActionPerformed

    private void jButton_BRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BRActionPerformed
       graficador.Animation("RIGHT", 4, 500);
    }//GEN-LAST:event_jButton_BRActionPerformed

    private void jButton_BDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BDActionPerformed
       graficador.Animation("DOWN", 4, 500);
    }//GEN-LAST:event_jButton_BDActionPerformed
 
    private void jButton_BUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BUActionPerformed
       graficador.Animation("UP", 4, 500);
    }//GEN-LAST:event_jButton_BUActionPerformed

    private void jButton_TESTER1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TESTER1ActionPerformed
       graficador.IncreaseTextSize();
    }//GEN-LAST:event_jButton_TESTER1ActionPerformed

    
    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    public String AbrirArchivo(File archivo){
        String documento = "";
        try{
            entrada = new FileInputStream(archivo);
            int ascci;
            while((ascci=entrada.read())!=-1){
                char caracter = (char)ascci;
                documento+=caracter;
            }
        }catch(Exception e){
            
        }
        return documento;
    }
    
    public String GuardarArchivo(File archivo, String documento){
        String mensaje = null;
        try{
            salida = new FileOutputStream(archivo);
            byte[] bytext = documento.getBytes();
            salida.write(bytext);
            mensaje = "Archivo guardado";
        }catch(Exception e){}
        return mensaje;
    }
    
    
    private void jButton_GuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarComoActionPerformed
        if(seleccionar.showDialog(null, "Guardar como")== JFileChooser.APPROVE_OPTION){
            archivo = seleccionar.getSelectedFile();
            if(archivo.getName().endsWith("bl")){
                String documento; // jtextpane.getText();
                //https://es.stackoverflow.com/questions/93136/buscar-archivos-por-extensi%C3%B3n-por-nombre-inicial-y-evaluar-contenido-de-arrayli
                //jtextpane.setText(documento);
            }else{
                JOptionPane.showMessageDialog(null, "Archivo no compatible.");
            }
        }
    }//GEN-LAST:event_jButton_GuardarComoActionPerformed

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_GuardarActionPerformed

    
    
    private void jButton_AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AbrirActionPerformed
        if(seleccionar.showDialog(null, "Abrir")== JFileChooser.APPROVE_OPTION){
            archivo = seleccionar.getSelectedFile();
            if(archivo.getName().endsWith("bl")){
                String documento = AbrirArchivo(archivo);
                //jtextpane.setText(documento);
            }else{
                JOptionPane.showMessageDialog(null, "Archivo no compatible.");
            }
        }
        
    }//GEN-LAST:event_jButton_AbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Abrir;
    private javax.swing.JButton jButton_BD;
    private javax.swing.JButton jButton_BL;
    private javax.swing.JButton jButton_BR;
    private javax.swing.JButton jButton_BU;
    private javax.swing.JButton jButton_D;
    private javax.swing.JButton jButton_Graficar;
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JButton jButton_GuardarComo;
    private javax.swing.JButton jButton_L;
    private javax.swing.JButton jButton_R;
    private javax.swing.JButton jButton_TESTER1;
    private javax.swing.JButton jButton_TESTER2;
    private javax.swing.JButton jButton_U;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
