/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tester;
import TwoDimensionalLists.*;
import LedAnimations.*;
import java.io.*;
import javax.swing.*;
import FileMananger.*;
import java.awt.event.ItemEvent;
/**
 *
 * @author alumno
 */
public class TesterEditor extends javax.swing.JFrame {

    /**
     * Creates new form TesterEditor
     */
    public TesterEditor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton_Nuevo = new javax.swing.JButton();
        jButton_Abrir = new javax.swing.JButton();
        jButton_Guardar = new javax.swing.JButton();
        jButton_GuardarComo = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSpinner_Retardo = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jSpinner_Posiciones = new javax.swing.JSpinner();
        jButton_AgregarSecuencia = new javax.swing.JButton();
        jComboBox_Direcciones = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner_NumeroFilas = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jSpinner_NumeroColumnas = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_CaracterApagado = new javax.swing.JTextField();
        jTextField_CaracterEncendido = new javax.swing.JTextField();
        jButton_ModificarTabla = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jComboBox_TipoPlano = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jComboBox_SecuenciaDirecciones = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jSpinner_SecuenciaPosiciones = new javax.swing.JSpinner();
        jSpinner_SecuenciaRetardo = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton_Pausa = new javax.swing.JButton();
        jButton_Aminar = new javax.swing.JButton();
        checkbox_Bucle = new java.awt.Checkbox();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextField_Texto = new javax.swing.JTextField();
        jComboBox_TipoElemento = new javax.swing.JComboBox<>();
        jButton_Graficar = new javax.swing.JButton();
        jComboBox_MovimientosSimples = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton_AumentarTamaño = new javax.swing.JButton();
        jButton_DisminuirTamaño = new javax.swing.JButton();
        jButton_Izquierda = new javax.swing.JButton();
        jButton_Arriba = new javax.swing.JButton();
        jButton_Derecha = new javax.swing.JButton();
        jButton_Abajo = new javax.swing.JButton();
        jButton_DiagonalARIZ = new javax.swing.JButton();
        jButton_DiagonalARDE = new javax.swing.JButton();
        jButton_DiagonalABDE = new javax.swing.JButton();
        jButton_DiagonalABIZ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane_Pantalla = new javax.swing.JTextPane();
        jLabel_NombreArchivo = new javax.swing.JLabel();
        jLabel_UrlArchivo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(230, 230, 230));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(235, 235, 235));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones de archivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 11))); // NOI18N
        jPanel5.setLayout(null);

        jButton_Nuevo.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Nuevo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_Nuevo.setText("Nuevo");
        jButton_Nuevo.setBorderPainted(false);
        jButton_Nuevo.setFocusable(false);
        jButton_Nuevo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton_Nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(jButton_Nuevo);
        jButton_Nuevo.setBounds(10, 20, 140, 50);

        jButton_Abrir.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Abrir.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_Abrir.setText("Abrir");
        jButton_Abrir.setBorderPainted(false);
        jButton_Abrir.setFocusable(false);
        jButton_Abrir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton_Abrir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton_Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AbrirActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_Abrir);
        jButton_Abrir.setBounds(150, 20, 140, 50);

        jButton_Guardar.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Guardar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_Guardar.setText("Guardar");
        jButton_Guardar.setBorderPainted(false);
        jButton_Guardar.setFocusable(false);
        jButton_Guardar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton_Guardar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_Guardar);
        jButton_Guardar.setBounds(10, 70, 140, 50);

        jButton_GuardarComo.setBackground(new java.awt.Color(102, 102, 102));
        jButton_GuardarComo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_GuardarComo.setText("Guardar como");
        jButton_GuardarComo.setBorderPainted(false);
        jButton_GuardarComo.setFocusable(false);
        jButton_GuardarComo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton_GuardarComo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton_GuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarComoActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_GuardarComo);
        jButton_GuardarComo.setBounds(150, 70, 140, 50);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(0, 5, 300, 130);

        jPanel6.setBackground(new java.awt.Color(235, 235, 235));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones de Animaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 11))); // NOI18N
        jPanel6.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel7.setText("Retardo:");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(210, 30, 80, 15);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel11.setText("Posiciones:");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(120, 30, 80, 15);

        jSpinner_Retardo.setValue(500);
        jPanel6.add(jSpinner_Retardo);
        jSpinner_Retardo.setBounds(210, 50, 80, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel12.setText("Dirección:");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(10, 30, 100, 15);
        jPanel6.add(jSpinner_Posiciones);
        jSpinner_Posiciones.setBounds(120, 50, 80, 30);

        jButton_AgregarSecuencia.setText("Agregar secuencia");
        jButton_AgregarSecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgregarSecuenciaActionPerformed(evt);
            }
        });
        jPanel6.add(jButton_AgregarSecuencia);
        jButton_AgregarSecuencia.setBounds(10, 90, 280, 40);

        jComboBox_Direcciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NORTE", "SUR", "ESTE", "OESTE", "NORESTE", "NOROESTE", "SURESTE", "SUROESTE", "INCREMENTAR", "DISMINUIR" }));
        jPanel6.add(jComboBox_Direcciones);
        jComboBox_Direcciones.setBounds(10, 50, 100, 30);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(0, 330, 300, 140);

        jPanel7.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificación de tabla", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 11))); // NOI18N
        jPanel7.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setText("Filas :");
        jPanel7.add(jLabel6);
        jLabel6.setBounds(10, 70, 30, 15);
        jPanel7.add(jSpinner_NumeroFilas);
        jSpinner_NumeroFilas.setBounds(50, 60, 80, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel13.setText("Apagado:");
        jPanel7.add(jLabel13);
        jLabel13.setBounds(150, 110, 60, 15);
        jPanel7.add(jSpinner_NumeroColumnas);
        jSpinner_NumeroColumnas.setBounds(210, 60, 80, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel14.setText("Columnas:");
        jPanel7.add(jLabel14);
        jLabel14.setBounds(150, 70, 60, 15);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel15.setText("Encendido:");
        jPanel7.add(jLabel15);
        jLabel15.setBounds(10, 110, 60, 15);
        jPanel7.add(jTextField_CaracterApagado);
        jTextField_CaracterApagado.setBounds(220, 100, 70, 30);
        jPanel7.add(jTextField_CaracterEncendido);
        jTextField_CaracterEncendido.setBounds(70, 100, 60, 30);

        jButton_ModificarTabla.setText("Modificar Banner");
        jButton_ModificarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModificarTablaActionPerformed(evt);
            }
        });
        jPanel7.add(jButton_ModificarTabla);
        jButton_ModificarTabla.setBounds(10, 140, 280, 40);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel20.setText("Tipo de gráfico:");
        jPanel7.add(jLabel20);
        jLabel20.setBounds(10, 30, 100, 15);

        jComboBox_TipoPlano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLANO AUTOMÁTICO", "PLANO DEFINIDO" }));
        jPanel7.add(jComboBox_TipoPlano);
        jComboBox_TipoPlano.setBounds(120, 20, 170, 30);

        jPanel4.add(jPanel7);
        jPanel7.setBounds(0, 140, 300, 190);

        jPanel8.setBackground(new java.awt.Color(235, 235, 235));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ejecución de animaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 11))); // NOI18N
        jPanel8.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jPanel8.setLayout(null);

        jComboBox_SecuenciaDirecciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_SecuenciaDireccionesItemStateChanged(evt);
            }
        });
        jPanel8.add(jComboBox_SecuenciaDirecciones);
        jComboBox_SecuenciaDirecciones.setBounds(10, 40, 100, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel16.setText("Dirección:");
        jPanel8.add(jLabel16);
        jLabel16.setBounds(10, 20, 100, 15);
        jPanel8.add(jSpinner_SecuenciaPosiciones);
        jSpinner_SecuenciaPosiciones.setBounds(120, 40, 80, 30);

        jSpinner_SecuenciaRetardo.setValue(500);
        jPanel8.add(jSpinner_SecuenciaRetardo);
        jSpinner_SecuenciaRetardo.setBounds(210, 40, 80, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel17.setText("Posiciones:");
        jPanel8.add(jLabel17);
        jLabel17.setBounds(120, 20, 80, 15);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel19.setText("Retardo:");
        jPanel8.add(jLabel19);
        jLabel19.setBounds(210, 20, 80, 15);

        jButton_Pausa.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_Pausa.setText("Pausar");
        jButton_Pausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PausaActionPerformed(evt);
            }
        });
        jPanel8.add(jButton_Pausa);
        jButton_Pausa.setBounds(10, 110, 140, 40);

        jButton_Aminar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_Aminar.setText("Animar");
        jButton_Aminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AminarActionPerformed(evt);
            }
        });
        jPanel8.add(jButton_Aminar);
        jButton_Aminar.setBounds(150, 110, 140, 40);

        checkbox_Bucle.setLabel("Activar repetición infinita (bucles).");
        jPanel8.add(checkbox_Bucle);
        checkbox_Bucle.setBounds(10, 80, 220, 20);

        jPanel4.add(jPanel8);
        jPanel8.setBounds(0, 470, 300, 160);

        jPanel3.setBackground(new java.awt.Color(220, 220, 220));
        jPanel3.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(225, 225, 225));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elementos a mostrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 11))); // NOI18N
        jPanel1.setLayout(null);
        jPanel1.add(jTextField_Texto);
        jTextField_Texto.setBounds(180, 20, 160, 30);

        jComboBox_TipoElemento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEXTO", "FORMAS" }));
        jPanel1.add(jComboBox_TipoElemento);
        jComboBox_TipoElemento.setBounds(10, 20, 160, 30);

        jButton_Graficar.setText("Graficar");
        jButton_Graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GraficarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Graficar);
        jButton_Graficar.setBounds(10, 60, 330, 35);

        jComboBox_MovimientosSimples.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOVIMIENTO EN PASOS", "MOVIMIENTO EN BUCLE", "MOVIMIENTO PAUSADO" }));
        jComboBox_MovimientosSimples.setDoubleBuffered(true);
        jPanel1.add(jComboBox_MovimientosSimples);
        jComboBox_MovimientosSimples.setBounds(180, 100, 160, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel18.setText("Tipo de movimiento en pantalla:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 110, 170, 15);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(3, 4, 350, 140);

        jPanel2.setBackground(new java.awt.Color(225, 225, 225));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Movimientos en pantalla", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 11))); // NOI18N
        jPanel2.setLayout(null);

        jButton_AumentarTamaño.setBackground(new java.awt.Color(102, 102, 102));
        jButton_AumentarTamaño.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_AumentarTamaño.setText("Aumentar tamaño");
        jButton_AumentarTamaño.setBorderPainted(false);
        jButton_AumentarTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AumentarTamañoActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_AumentarTamaño);
        jButton_AumentarTamaño.setBounds(10, 20, 130, 60);

        jButton_DisminuirTamaño.setBackground(new java.awt.Color(102, 102, 102));
        jButton_DisminuirTamaño.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_DisminuirTamaño.setText("Disminuir tamaño");
        jButton_DisminuirTamaño.setBorderPainted(false);
        jButton_DisminuirTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DisminuirTamañoActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_DisminuirTamaño);
        jButton_DisminuirTamaño.setBounds(10, 80, 130, 60);

        jButton_Izquierda.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Izquierda.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_Izquierda.setText("OESTE");
        jButton_Izquierda.setBorderPainted(false);
        jButton_Izquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IzquierdaActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Izquierda);
        jButton_Izquierda.setBounds(150, 60, 140, 40);

        jButton_Arriba.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Arriba.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_Arriba.setText("NORTE");
        jButton_Arriba.setBorderPainted(false);
        jButton_Arriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ArribaActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Arriba);
        jButton_Arriba.setBounds(240, 20, 90, 40);

        jButton_Derecha.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Derecha.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_Derecha.setText("ESTE");
        jButton_Derecha.setBorderPainted(false);
        jButton_Derecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DerechaActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Derecha);
        jButton_Derecha.setBounds(290, 60, 130, 40);

        jButton_Abajo.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Abajo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_Abajo.setText("SUR");
        jButton_Abajo.setBorderPainted(false);
        jButton_Abajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AbajoActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Abajo);
        jButton_Abajo.setBounds(240, 100, 90, 40);

        jButton_DiagonalARIZ.setBackground(new java.awt.Color(102, 102, 102));
        jButton_DiagonalARIZ.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_DiagonalARIZ.setText("NOROESTE");
        jButton_DiagonalARIZ.setBorderPainted(false);
        jButton_DiagonalARIZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DiagonalARIZActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_DiagonalARIZ);
        jButton_DiagonalARIZ.setBounds(150, 20, 90, 40);

        jButton_DiagonalARDE.setBackground(new java.awt.Color(102, 102, 102));
        jButton_DiagonalARDE.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_DiagonalARDE.setText("NORESTE");
        jButton_DiagonalARDE.setBorderPainted(false);
        jButton_DiagonalARDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DiagonalARDEActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_DiagonalARDE);
        jButton_DiagonalARDE.setBounds(330, 20, 90, 40);

        jButton_DiagonalABDE.setBackground(new java.awt.Color(102, 102, 102));
        jButton_DiagonalABDE.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_DiagonalABDE.setText("SURESTE");
        jButton_DiagonalABDE.setBorderPainted(false);
        jButton_DiagonalABDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DiagonalABDEActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_DiagonalABDE);
        jButton_DiagonalABDE.setBounds(330, 100, 90, 40);

        jButton_DiagonalABIZ.setBackground(new java.awt.Color(102, 102, 102));
        jButton_DiagonalABIZ.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_DiagonalABIZ.setText("SUROESTE");
        jButton_DiagonalABIZ.setBorderPainted(false);
        jButton_DiagonalABIZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DiagonalABIZActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_DiagonalABIZ);
        jButton_DiagonalABIZ.setBounds(150, 100, 90, 40);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(360, 4, 430, 140);

        jTextPane_Pantalla.setEditable(false);
        jTextPane_Pantalla.setBackground(new java.awt.Color(250, 250, 250));
        jTextPane_Pantalla.setBorder(null);
        jTextPane_Pantalla.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jTextPane_Pantalla.setDoubleBuffered(true);
        jScrollPane1.setViewportView(jTextPane_Pantalla);

        jLabel_NombreArchivo.setBackground(new java.awt.Color(250, 250, 250));
        jLabel_NombreArchivo.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_NombreArchivo.setText("Archivo sin nombre");
        jLabel_NombreArchivo.setOpaque(true);

        jLabel_UrlArchivo.setBackground(new java.awt.Color(245, 245, 245));
        jLabel_UrlArchivo.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_UrlArchivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_UrlArchivo.setText("Archivo aún no guardado");
        jLabel_UrlArchivo.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_NombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jLabel_UrlArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_NombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_UrlArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(5, 5, 5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ITwoDimensionalLists tabla;
    SwingGraphicsLedScreen graficador;
    private int columnas, filas;
    private char encendido, apagado;
    private String instruccion = "", modo, texto, matriz;
    int i = 0; String[] direcciones = new String[1024]; int[] posiciones = new int[1024], retardo = new int[1024];
    String d = "";
    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    private void jButton_AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AbrirActionPerformed
        if(seleccionar.showDialog(null, "Abrir")== JFileChooser.APPROVE_OPTION){
            archivo = seleccionar.getSelectedFile();
            if(archivo.getName().endsWith("bl")){
                String documento = FileMananger.AbrirArchivo(archivo);
                //jtextpane.setText(documento);
            }else{
                JOptionPane.showMessageDialog(null, "Archivo no compatible.");
            }
        }
    }//GEN-LAST:event_jButton_AbrirActionPerformed

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_GuardarActionPerformed

    private void jButton_GuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarComoActionPerformed
        matriz = tabla.getMatrix();
        String datos = ""+filas + "<-->" + columnas + "<-->" + encendido +"<-->" + apagado + "<-->" + texto +
        "\n<-->"+ matriz + "<-->"+
        instruccion;

        if(seleccionar.showDialog(null, "Guardar como")== JFileChooser.APPROVE_OPTION){
            archivo = seleccionar.getSelectedFile();
            if(archivo.getName().endsWith("bl")){
                String documento =  datos;
                String mensaje = FileMananger.GuardarArchivo2(archivo, documento);
                if(mensaje!=null){
                    JOptionPane.showMessageDialog(null, mensaje);
                }else{JOptionPane.showMessageDialog(null, "Archivo no compatible.");}
                // jtextpane.getText();
                //https://es.stackoverflow.com/questions/93136/buscar-archivos-por-extensi%C3%B3n-por-nombre-inicial-y-evaluar-contenido-de-arrayli
                //jtextpane.setText(documento);
            }else{
                JOptionPane.showMessageDialog(null, "Archivo no compatible.");
            }
        }
    }//GEN-LAST:event_jButton_GuardarComoActionPerformed

    private void jButton_AgregarSecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgregarSecuenciaActionPerformed
        if(jComboBox_Direcciones.getSelectedItem() == "NORTE"){
            direcciones[i] = "NORTE";
        }
        else if(jComboBox_Direcciones.getSelectedItem() == "SUR"){
            direcciones[i] = "SUR";
        }
        else if(jComboBox_Direcciones.getSelectedItem() == "ESTE"){
            direcciones[i] = "ESTE";
        }
        else if(jComboBox_Direcciones.getSelectedItem() == "OESTE"){
            direcciones[i] = "OESTE";
        }

        else if(jComboBox_Direcciones.getSelectedItem() == "NORESTE"){
            direcciones[i] = "NORESTE";
        }
        else if(jComboBox_Direcciones.getSelectedItem() == "NOROESTE"){
            direcciones[i] = "NOROESTE";
        }
        else if(jComboBox_Direcciones.getSelectedItem() == "SUROESTE"){
            direcciones[i] = "SUROESTE";
        }
        else if(jComboBox_Direcciones.getSelectedItem() == "SURESTE"){
            direcciones[i] = "SURESTE";
        }
        else if(jComboBox_Direcciones.getSelectedItem() == "INCREMENTAR"){
            direcciones[i] = "INCREMENTAR";
        }
        else if(jComboBox_Direcciones.getSelectedItem() == "DISMINUIR"){
            direcciones[i] = "DISMINUIR";
        }
        jComboBox_SecuenciaDirecciones.addItem(direcciones[i]);
        posiciones[i] = Integer.parseInt(jSpinner_Posiciones.getValue().toString());
        retardo[i] = Integer.parseInt(jSpinner_Retardo.getValue().toString());
        jSpinner_SecuenciaPosiciones.setValue(posiciones[i]);
        jSpinner_SecuenciaRetardo.setValue(retardo[i]);
        i++;
    }//GEN-LAST:event_jButton_AgregarSecuenciaActionPerformed

    private void jButton_ModificarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModificarTablaActionPerformed
        encendido = jTextField_CaracterEncendido.getText().charAt(0);
        apagado = jTextField_CaracterApagado.getText().charAt(0);
        if(jComboBox_TipoPlano.getSelectedItem() == "PLANO AUTOMÁTICO"){
            tabla = new TwoDimensionalLists(jTextField_Texto.getText(), encendido ,apagado);
            filas = 8; columnas = tabla.getText().length()/filas;
        }
        else if(jComboBox_TipoPlano.getSelectedItem() == "PLANO DEFINIDO"){
            filas = Integer.parseInt(jSpinner_NumeroFilas.getValue().toString());
            columnas = Integer.parseInt(jSpinner_NumeroColumnas.getValue().toString());
            tabla = new TwoDimensionalLists(filas,columnas , encendido,apagado);
        }

        graficador = new SwingGraphicsLedScreen((TwoDimensionalLists)tabla, jTextPane_Pantalla);
        jTextPane_Pantalla.setText(tabla.getText());
    }//GEN-LAST:event_jButton_ModificarTablaActionPerformed

    private void jComboBox_SecuenciaDireccionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_SecuenciaDireccionesItemStateChanged
        int k = ItemEvent.SELECTED;
        jTextPane_Pantalla.setText(""+k);
        /*jSpinner_SecuenciaPosiciones.setValue(posiciones[k]);
        jSpinner_SecuenciaRetardo.setValue(retardo[k]);*/
    }//GEN-LAST:event_jComboBox_SecuenciaDireccionesItemStateChanged

    private void jButton_PausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PausaActionPerformed
        graficador.StopAnimation();
    }//GEN-LAST:event_jButton_PausaActionPerformed

    private void jButton_AminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AminarActionPerformed
        if(checkbox_Bucle.getState() == true){
            modo = "BUCLE";
        }else{modo = "VIEW";}
        instruccion = getInstruction() + "/" + modo;
        graficador.SequentialAnimation(instruccion);
    }//GEN-LAST:event_jButton_AminarActionPerformed

    private void jButton_GraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GraficarActionPerformed
        if(jComboBox_TipoElemento.getSelectedItem() == "TEXTO"){
            texto = jTextField_Texto.getText();
        }else if(jComboBox_TipoElemento.getSelectedItem() == "FORMAS"){
            texto = "figures:" + jTextField_Texto.getText();
        }
        graficador.GraphLedDisplay(texto);
    }//GEN-LAST:event_jButton_GraficarActionPerformed

    private void jButton_AumentarTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AumentarTamañoActionPerformed
        graficador.IncreaseTextSize();
    }//GEN-LAST:event_jButton_AumentarTamañoActionPerformed

    private void jButton_DisminuirTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DisminuirTamañoActionPerformed
        graficador.DecreaseTextSize();
    }//GEN-LAST:event_jButton_DisminuirTamañoActionPerformed

    private void jButton_IzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IzquierdaActionPerformed
        graficador.MoveOneStepLeft();
    }//GEN-LAST:event_jButton_IzquierdaActionPerformed

    private void jButton_ArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ArribaActionPerformed
        graficador.MoveOneStepUp();
    }//GEN-LAST:event_jButton_ArribaActionPerformed

    private void jButton_DerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DerechaActionPerformed
        graficador.MoveOneStepRight();
    }//GEN-LAST:event_jButton_DerechaActionPerformed

    private void jButton_AbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AbajoActionPerformed
        graficador.MoveOneStepDown();
    }//GEN-LAST:event_jButton_AbajoActionPerformed

    private void jButton_DiagonalARIZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DiagonalARIZActionPerformed
        graficador.MoveOneStepUpLeft();
    }//GEN-LAST:event_jButton_DiagonalARIZActionPerformed

    private void jButton_DiagonalARDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DiagonalARDEActionPerformed
        graficador.MoveOneStepUpRight();
    }//GEN-LAST:event_jButton_DiagonalARDEActionPerformed

    private void jButton_DiagonalABDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DiagonalABDEActionPerformed
        graficador.MoveOneStepDownRight();
    }//GEN-LAST:event_jButton_DiagonalABDEActionPerformed

    private void jButton_DiagonalABIZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DiagonalABIZActionPerformed
        graficador.MoveOneStepDownLeft();
    }//GEN-LAST:event_jButton_DiagonalABIZActionPerformed

    private String getInstruction(){
        String[] newDireccion= new String[]{"DIAGONALARDE","DIAGONALARIZ","DIAGONALABDE","DIAGONALABIZ", "ARRIBA", "ABAJO", "DERECHA", "IZQUIERDA"};
        String[] olddirection= new String[]{"NORESTE", "NOROESTE", "SURESTE", "SUROESTE","NORTE", "SUR","ESTE", "OESTE"};
        String secuencia = "";
        for(int i = 0; i < this.i; i++){
            String intruccion = direcciones[i] + ":" + posiciones[i] + "-" + retardo[i];
            secuencia += intruccion; 
            if(i<this.i -1){
                secuencia += "_";
            }
        }
        for(int i = 0; i< olddirection.length; i++){
            secuencia = secuencia.replaceAll(olddirection[i], newDireccion[i]);
        }
        return secuencia;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesterEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesterEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesterEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesterEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesterEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkbox_Bucle;
    private javax.swing.JButton jButton_Abajo;
    private javax.swing.JButton jButton_Abrir;
    private javax.swing.JButton jButton_AgregarSecuencia;
    private javax.swing.JButton jButton_Aminar;
    private javax.swing.JButton jButton_Arriba;
    private javax.swing.JButton jButton_AumentarTamaño;
    private javax.swing.JButton jButton_Derecha;
    private javax.swing.JButton jButton_DiagonalABDE;
    private javax.swing.JButton jButton_DiagonalABIZ;
    private javax.swing.JButton jButton_DiagonalARDE;
    private javax.swing.JButton jButton_DiagonalARIZ;
    private javax.swing.JButton jButton_DisminuirTamaño;
    private javax.swing.JButton jButton_Graficar;
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JButton jButton_GuardarComo;
    private javax.swing.JButton jButton_Izquierda;
    private javax.swing.JButton jButton_ModificarTabla;
    private javax.swing.JButton jButton_Nuevo;
    private javax.swing.JButton jButton_Pausa;
    private javax.swing.JComboBox<String> jComboBox_Direcciones;
    private javax.swing.JComboBox<String> jComboBox_MovimientosSimples;
    private javax.swing.JComboBox<String> jComboBox_SecuenciaDirecciones;
    private javax.swing.JComboBox<String> jComboBox_TipoElemento;
    private javax.swing.JComboBox<String> jComboBox_TipoPlano;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_NombreArchivo;
    private javax.swing.JLabel jLabel_UrlArchivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_NumeroColumnas;
    private javax.swing.JSpinner jSpinner_NumeroFilas;
    private javax.swing.JSpinner jSpinner_Posiciones;
    private javax.swing.JSpinner jSpinner_Retardo;
    private javax.swing.JSpinner jSpinner_SecuenciaPosiciones;
    private javax.swing.JSpinner jSpinner_SecuenciaRetardo;
    private javax.swing.JTextField jTextField_CaracterApagado;
    private javax.swing.JTextField jTextField_CaracterEncendido;
    private javax.swing.JTextField jTextField_Texto;
    private javax.swing.JTextPane jTextPane_Pantalla;
    // End of variables declaration//GEN-END:variables
}
