/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import FileMananger.FileMananger;
import LedAnimations.SwingGraphicsLedScreen;
import Listas.Aleatoria;
import TwoDimensionalLists.*;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author neuro
 */
public class InicioEditor extends javax.swing.JFrame {

    /**
     * Creates new form InicioEditor
     */
    public InicioEditor() {
        initComponents();
    }
    
    public InicioEditor(boolean visor) {
        this.visor = visor;
        initComponents();
    }
    
    
    ITwoDimensionalLists tabla;
    SwingGraphicsLedScreen graficador;
    private int columnas, filas;
    private char encendido, apagado;
    private String instruccion = "", modo, texto, matriz;
    int i = 0; Aleatoria direcciones = new Aleatoria(), posiciones = new Aleatoria(), retardo = new Aleatoria();
    boolean visor;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_TipoPlano = new javax.swing.JPanel();
        jComboBox_TipoPlano = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel_TipoGrafico = new javax.swing.JPanel();
        jComboBox_TipoGrafico = new javax.swing.JComboBox<>();
        jTextField_TextoFigura = new javax.swing.JTextField();
        jSpinner_NumeroFilas = new javax.swing.JSpinner();
        jSpinner_NumeroColumnas = new javax.swing.JSpinner();
        jTextField_CaracterEncendido = new javax.swing.JTextField();
        jTextField_CaracterApagado = new javax.swing.JTextField();
        jButton_CrearPlano = new javax.swing.JButton();
        jButton_AbrirArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rensteom BannerLed Elemental Editor");
        setMinimumSize(new java.awt.Dimension(360, 390));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel_TipoPlano.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de plano"));
        jPanel_TipoPlano.setLayout(null);

        jComboBox_TipoPlano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLANO BIDIMENSIONAL DEFINIDO", "PLANO BIDIMENSIONAL AUTOMÁTICO" }));
        jComboBox_TipoPlano.setFocusable(false);
        jPanel_TipoPlano.add(jComboBox_TipoPlano);
        jComboBox_TipoPlano.setBounds(10, 20, 300, 30);

        getContentPane().add(jPanel_TipoPlano);
        jPanel_TipoPlano.setBounds(10, 130, 320, 60);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(17, 10, 310, 110);
        javax.swing.ImageIcon imageLogo = new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"));
        java.awt.Image escalada = imageLogo.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), java.awt.Image.SCALE_DEFAULT);
        javax.swing.Icon iconLogo = new javax.swing.ImageIcon(escalada);
        jLabel1.setIcon(iconLogo);

        jPanel_TipoGrafico.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de gráfico"));
        jPanel_TipoGrafico.setLayout(null);

        jComboBox_TipoGrafico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEXTO", "FIGURAS" }));
        jComboBox_TipoGrafico.setFocusable(false);
        jComboBox_TipoGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TipoGraficoActionPerformed(evt);
            }
        });
        jPanel_TipoGrafico.add(jComboBox_TipoGrafico);
        jComboBox_TipoGrafico.setBounds(10, 20, 90, 30);

        getContentPane().add(jPanel_TipoGrafico);
        jPanel_TipoGrafico.setBounds(10, 190, 110, 60);

        jTextField_TextoFigura.setBorder(javax.swing.BorderFactory.createTitledBorder("Texto a graficar:"));
        getContentPane().add(jTextField_TextoFigura);
        jTextField_TextoFigura.setBounds(120, 200, 210, 40);

        jSpinner_NumeroFilas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 10));
        jSpinner_NumeroFilas.setBorder(javax.swing.BorderFactory.createTitledBorder("Filas"));
        getContentPane().add(jSpinner_NumeroFilas);
        jSpinner_NumeroFilas.setBounds(10, 250, 80, 41);

        jSpinner_NumeroColumnas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 10));
        jSpinner_NumeroColumnas.setBorder(javax.swing.BorderFactory.createTitledBorder("Columnas"));
        getContentPane().add(jSpinner_NumeroColumnas);
        jSpinner_NumeroColumnas.setBounds(90, 250, 80, 41);

        jTextField_CaracterEncendido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_CaracterEncendido.setText("⬛");
        jTextField_CaracterEncendido.setBorder(javax.swing.BorderFactory.createTitledBorder("Encendido"));
        getContentPane().add(jTextField_CaracterEncendido);
        jTextField_CaracterEncendido.setBounds(170, 250, 80, 41);

        jTextField_CaracterApagado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_CaracterApagado.setText("⬜");
        jTextField_CaracterApagado.setBorder(javax.swing.BorderFactory.createTitledBorder("Apagado"));
        getContentPane().add(jTextField_CaracterApagado);
        jTextField_CaracterApagado.setBounds(250, 250, 80, 41);

        jButton_CrearPlano.setText("Crear BannerLed");
        jButton_CrearPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearPlanoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_CrearPlano);
        jButton_CrearPlano.setBounds(170, 300, 159, 40);

        jButton_AbrirArchivo.setText("Abrir Archivo");
        jButton_AbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AbrirArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_AbrirArchivo);
        jButton_AbrirArchivo.setBounds(10, 300, 159, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CrearPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearPlanoActionPerformed
        encendido = jTextField_CaracterEncendido.getText().charAt(0);
        apagado = jTextField_CaracterApagado.getText().charAt(0);
        
        if(encendido == apagado){jTextField_CaracterEncendido.setText(""); jTextField_CaracterApagado.setText(""); JOptionPane.showMessageDialog(null, "Esto se debe a que los caracteres de encendido y apagado son iguales. Cambielos para lograr realizar su gráfico.", "CARACTERES IGUALES", 1);return;}
        else if(encendido == ' ' || apagado == ' '){ jTextField_CaracterEncendido.setText(""); jTextField_CaracterApagado.setText(""); JOptionPane.showMessageDialog(null, "Esto se debe a que los caracteres de encendido o apagado contienen algún caracter inválido e incompatible con la estructura de los archivos \".bl\"", "CARACTER INVÁLIDO PARA EL GRÁFICO", 0);return;}
        
        
        if(jComboBox_TipoGrafico.getSelectedItem() == "TEXTO"){texto =  "text:" + jTextField_TextoFigura.getText();}
        else if(jComboBox_TipoGrafico.getSelectedItem() == "FIGURAS"){texto = "figures:" + jTextField_TextoFigura.getText();}

        try{
            if(jComboBox_TipoPlano.getSelectedItem() == "PLANO BIDIMENSIONAL AUTOMÁTICO"){
                tabla = new TwoDimensionalLists(texto, encendido ,apagado);
                filas = tabla.rowLength(); columnas = tabla.columnLength();
            }
            else if(jComboBox_TipoPlano.getSelectedItem() == "PLANO BIDIMENSIONAL DEFINIDO"){
                filas = Integer.parseInt(jSpinner_NumeroFilas.getValue().toString());
                columnas = Integer.parseInt(jSpinner_NumeroColumnas.getValue().toString());
                tabla = new TwoDimensionalLists(filas,columnas , encendido,apagado);
                tabla.setText(texto);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Asegúrese que el archivo cuente por lo menos con un gráfico.","NO SE CREO EL PLANO", 0);
            return;
        }
        
        String config = jComboBox_TipoPlano.getSelectedItem()+ "-" + jComboBox_TipoGrafico.getSelectedItem() + "-" +texto
                + "-"+filas  + "-"+ columnas  + "-"+ encendido
                 + "-"+ apagado
                ;
        Editor editor = new Editor(tabla, config);
        if(visor == true){editor.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);}
        editor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_CrearPlanoActionPerformed

    private void jComboBox_TipoGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TipoGraficoActionPerformed
        com.mxrck.autocompleter.TextAutoCompleter tac = new com.mxrck.autocompleter.TextAutoCompleter(jTextField_TextoFigura);
        
        if (jComboBox_TipoGrafico.getSelectedItem() == "TEXTO") {
            jTextField_TextoFigura.setBorder(new javax.swing.border.TitledBorder("Texto a graficar:"));
            tac.removeAllItems();
        } else {
            jTextField_TextoFigura.setBorder(new javax.swing.border.TitledBorder("Elemento a graficar:"));
            tac.addItem("pelota");
            tac.addItem("auto");
            tac.addItem("corazon");
            tac.addItem("rombo");
            tac.addItem("humano");
            tac.addItem("barco");
            tac.addItem("serpiente");
            tac.addItem("tuerca");
            tac.addItem("puntero");
            tac.addItem("peligro");
            tac.addItem("estrella");
        }
    }//GEN-LAST:event_jComboBox_TipoGraficoActionPerformed
    String d = "";
    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    private void jButton_AbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AbrirArchivoActionPerformed
        if(seleccionar.showDialog(null, "Abrir")== JFileChooser.APPROVE_OPTION){
            archivo = seleccionar.getSelectedFile();
            if(archivo.getName().endsWith("bl")){
                String leerArchivo = FileMananger.AbrirArchivo(archivo);
                leerArchivo = leerArchivo + "<>" + archivo.toString();
                Editor editor = new Editor(leerArchivo);
                editor.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Archivo no compatible.");
            }
        }
    }//GEN-LAST:event_jButton_AbrirArchivoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/blStudio.png")).getImage());
    }//GEN-LAST:event_formWindowOpened

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AbrirArchivo;
    private javax.swing.JButton jButton_CrearPlano;
    private javax.swing.JComboBox<String> jComboBox_TipoGrafico;
    private javax.swing.JComboBox<String> jComboBox_TipoPlano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel_TipoGrafico;
    private javax.swing.JPanel jPanel_TipoPlano;
    private javax.swing.JSpinner jSpinner_NumeroColumnas;
    private javax.swing.JSpinner jSpinner_NumeroFilas;
    private javax.swing.JTextField jTextField_CaracterApagado;
    private javax.swing.JTextField jTextField_CaracterEncendido;
    private javax.swing.JTextField jTextField_TextoFigura;
    // End of variables declaration//GEN-END:variables
}
